//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChangedBlockDelta) DeepCopyInto(out *ChangedBlockDelta) {
	*out = *in
	in.DataToken.DeepCopyInto(&out.DataToken)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChangedBlockDelta.
func (in *ChangedBlockDelta) DeepCopy() *ChangedBlockDelta {
	if in == nil {
		return nil
	}
	out := new(ChangedBlockDelta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataToken) DeepCopyInto(out *DataToken) {
	*out = *in
	in.IssuanceTime.DeepCopyInto(&out.IssuanceTime)
	out.TTL = in.TTL
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataToken.
func (in *DataToken) DeepCopy() *DataToken {
	if in == nil {
		return nil
	}
	out := new(DataToken)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriverDiscovery) DeepCopyInto(out *DriverDiscovery) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriverDiscovery.
func (in *DriverDiscovery) DeepCopy() *DriverDiscovery {
	if in == nil {
		return nil
	}
	out := new(DriverDiscovery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DriverDiscovery) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriverDiscoveryList) DeepCopyInto(out *DriverDiscoveryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DriverDiscovery, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriverDiscoveryList.
func (in *DriverDiscoveryList) DeepCopy() *DriverDiscoveryList {
	if in == nil {
		return nil
	}
	out := new(DriverDiscoveryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DriverDiscoveryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriverDiscoverySpec) DeepCopyInto(out *DriverDiscoverySpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriverDiscoverySpec.
func (in *DriverDiscoverySpec) DeepCopy() *DriverDiscoverySpec {
	if in == nil {
		return nil
	}
	out := new(DriverDiscoverySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeSnapshotDelta) DeepCopyInto(out *VolumeSnapshotDelta) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeSnapshotDelta.
func (in *VolumeSnapshotDelta) DeepCopy() *VolumeSnapshotDelta {
	if in == nil {
		return nil
	}
	out := new(VolumeSnapshotDelta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VolumeSnapshotDelta) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeSnapshotDeltaList) DeepCopyInto(out *VolumeSnapshotDeltaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VolumeSnapshotDelta, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeSnapshotDeltaList.
func (in *VolumeSnapshotDeltaList) DeepCopy() *VolumeSnapshotDeltaList {
	if in == nil {
		return nil
	}
	out := new(VolumeSnapshotDeltaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VolumeSnapshotDeltaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeSnapshotDeltaOption) DeepCopyInto(out *VolumeSnapshotDeltaOption) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeSnapshotDeltaOption.
func (in *VolumeSnapshotDeltaOption) DeepCopy() *VolumeSnapshotDeltaOption {
	if in == nil {
		return nil
	}
	out := new(VolumeSnapshotDeltaOption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VolumeSnapshotDeltaOption) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeSnapshotDeltaSpec) DeepCopyInto(out *VolumeSnapshotDeltaSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeSnapshotDeltaSpec.
func (in *VolumeSnapshotDeltaSpec) DeepCopy() *VolumeSnapshotDeltaSpec {
	if in == nil {
		return nil
	}
	out := new(VolumeSnapshotDeltaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeSnapshotDeltaStatus) DeepCopyInto(out *VolumeSnapshotDeltaStatus) {
	*out = *in
	if in.ChangedBlockDeltas != nil {
		in, out := &in.ChangedBlockDeltas, &out.ChangedBlockDeltas
		*out = make([]*ChangedBlockDelta, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ChangedBlockDelta)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeSnapshotDeltaStatus.
func (in *VolumeSnapshotDeltaStatus) DeepCopy() *VolumeSnapshotDeltaStatus {
	if in == nil {
		return nil
	}
	out := new(VolumeSnapshotDeltaStatus)
	in.DeepCopyInto(out)
	return out
}
