FROM golang:1.17 as builder
WORKDIR /workspace
COPY go.mod go.mod
COPY go.sum go.sum
COPY vendor vendor
COPY pkg pkg
COPY ./cmd/mock/client/main.go main.go
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o backup-client main.go

FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=builder /workspace/backup-client .
USER 65532:65532
ENTRYPOINT ["/backup-client"]
